[project]
name = "algobattle"
version = "4.0.0"
readme = "README.md"
requires-python = ">=3.11"
license = {text = "MIT"}
authors = [{name = "Imogen Hergeth"}, {name = "Jan Dreier"}, {name = "Henri Lotze"}]
urls = {github = "https://github.com/Benezivas/algobattle"}
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Natural Language :: English",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Typing :: Typed",
]
dependencies = [
    # we need to use a fixed version of the docker lib for windows
    "docker @ git+https://github.com/ImogenBits/docker-py.git",

    # on windows, we need to manually install curses bindings
    "windows-curses; os_name == 'nt'",

    "prettytable",
    "pydantic",
    "anyio",
]

[project.scripts]
algobattle = "algobattle.cli:main"

[tool.pyright]
diagnosticMode = "workspace"
