[project]
name = "algobattle"
version = "4.0.0"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [{name = "Jan Dreier"}, {name = "Henri Lotze"}]

[project.scripts]
algobattle = "algobattle.battle:main"
