# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Algorithmic Battle

on:
  push:
    branches: [ main, develop, 4.0.0-rc ]
  pull_request:
    branches: [ main, develop, 4.0.0-rc ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
    - name: Lint with flake8
      run: flake8 .

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . --user
    - name: Test using unittests
      run: python -m unittest --failfast

  execute:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . --user
    - name: Run short battles with different options as a sanity check
      run: |
        algobattle algobattle/problems/testsproblem --verbose --config=algobattle/config/config_short_run_timeout.ini --rounds=2
        algobattle algobattle/problems/testsproblem --verbose --config=algobattle/config/config_short_run_timeout.ini --rounds=2 --generators=algobattle/problems/testsproblem/generator,algobattle/problems/testsproblem/generator --solvers=algobattle/problems/testsproblem/solver,algobattle/problems/testsproblem/solver --team_names=team1,team2
        algobattle algobattle/problems/testsproblem --verbose --config=algobattle/config/config_short_run_timeout.ini --battle_type=averaged --rounds=2
