# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Algorithmic Battle

on:
  push:
    branches: [ main, develop, 4.0.0-rc ]
  pull_request:
    branches: [ main, develop, 4.0.0-rc ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
    - name: Lint with flake8
      run: flake8 .

  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: install Docker
      if: runner.os == 'macOS'
      uses: docker-practice/actions-setup-docker@master
    - name: get fake alpine image for tests
      if: runner.os == 'Windows'
      run: |
        docker image tag mcr.microsoft.com/windows/servercore:ltsc2022 alpine
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . --user
    - name: Test using unittests
      run: python -m unittest --failfast

  execute:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: get fake alpine image for tests
      if: runner.os == 'Windows'
      run: |
        docker image tag mcr.microsoft.com/windows/servercore:ltsc2022 alpine
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install . --user
    - name: Run short battles with different options as a sanity check
      run: |
        algobattle tests/testsproblem --verbose --config=tests/testsproblem/config_short_run_timeout.ini --rounds=2
        algobattle tests/testsproblem --verbose --config=tests/testsproblem/config_short_run_timeout.ini --rounds=2 --generators=tests/testsproblem/generator,tests/testsproblem/generator --solvers=tests/testsproblem/solver,tests/testsproblem/solver --team_names=team1,team2
        algobattle tests/testsproblem --verbose --config=tests/testsproblem/config_short_run_timeout.ini --battle_type=averaged --rounds=2
